# This file was generated by GoReleaser. DO NOT EDIT.
cask "catacomb" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "55620696edf2f5e24dd59331969289442d312b41880228918244ac045ac8afa4"
      url "https://github.com/realkarych/catacomb/releases/download/v#{version}/v#{version}_catacomb_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "81b968beff149de8fceda88cb24cbf919a884ed8ca2e6d67d90b45f24e1480d0"
      url "https://github.com/realkarych/catacomb/releases/download/v#{version}/v#{version}_catacomb_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "18240b749616f32c23e605be130bb79be45a82598eeb613bfa0b893e5d0d032a"
      url "https://github.com/realkarych/catacomb/releases/download/v#{version}/v#{version}_catacomb_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a1b359b711fb237cec41869998b50820a5b4af4f4865fb38fe445644fc2109a0"
      url "https://github.com/realkarych/catacomb/releases/download/v#{version}/v#{version}_catacomb_linux_arm64.tar.gz"
    end
  end

  name "catacomb"
  desc "Offline eval gate for Claude Code agents"
  homepage "https://github.com/realkarych/catacomb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "catacomb"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/catacomb"]
    end
  end

  # No zap stanza required

end
