# This file was generated by GoReleaser. DO NOT EDIT.
cask "catacomb" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "4e13cc625aa517c3a143d44e73159eb0b8949513c1a6b7c29ecbfe5e69cc137b"
      url "https://github.com/realkarych/catacomb/releases/download/v#{version}/v#{version}_catacomb_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7393c4bf2585d14697e8e429f94f57e4d902a5bff90a27b0ab9b98da648ef975"
      url "https://github.com/realkarych/catacomb/releases/download/v#{version}/v#{version}_catacomb_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c5ae9e3e292e464d4611b5650f293337e9826a8ea5556295f18f80f1b392eeee"
      url "https://github.com/realkarych/catacomb/releases/download/v#{version}/v#{version}_catacomb_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "daf4f1b51b8b861c5fb693787ef84cf23cdd7a9312d665123f42e6216483233b"
      url "https://github.com/realkarych/catacomb/releases/download/v#{version}/v#{version}_catacomb_linux_arm64.tar.gz"
    end
  end

  name "catacomb"
  desc "Offline eval gate for Claude Code agentic pipelines"
  homepage "https://github.com/realkarych/catacomb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "catacomb"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/catacomb"]
    end
  end

  # No zap stanza required

end
