# This file was generated by GoReleaser. DO NOT EDIT.
cask "catacomb" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "6de1e80c412236da4f0821bbbe3c158ce87dd94d1eaae9a425ee97ee44863a81"
      url "https://github.com/realkarych/catacomb/releases/download/v#{version}/v#{version}_catacomb_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0968753f5f2e2bd7855219b77db3e8ee62ddaba82130961de99f46999c05cf65"
      url "https://github.com/realkarych/catacomb/releases/download/v#{version}/v#{version}_catacomb_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "944dbc1f77e6329694542a475b3dcbd5549a7a7faa5d539fe275be880332d42e"
      url "https://github.com/realkarych/catacomb/releases/download/v#{version}/v#{version}_catacomb_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6207f3ee686107b15c47ce3b19081d136857362aa9f1a600475c4ee2878e07dc"
      url "https://github.com/realkarych/catacomb/releases/download/v#{version}/v#{version}_catacomb_linux_arm64.tar.gz"
    end
  end

  name "catacomb"
  desc "Offline eval gate for Claude Code agentic pipelines"
  homepage "https://github.com/realkarych/catacomb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "catacomb"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/catacomb"]
    end
  end

  # No zap stanza required

end
